### ISSUE TITLE
Build failing due to linking error

### ISSUE THREAD

**Issue by debloper** [Coeuvre/rust-2048#14]
```
note: /usr/bin/ld: cannot find -lSDL2
/usr/bin/ld: cannot find -lSDL2
collect2: error: ld returned 1 exit status
```

**Comment by juninho** [comment]
Hi, have you ever tried install libsdl-dev?
# apt-get install libsdl2-dev

**Comment by kefirchik** [comment]
On win, libsdl2 installation solves this kind of problems, I think u can close this issue :wink:
